name = "Puppy Modpack"
author = "luanalatte"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c9582bb08b8c2461c98cf42a258086c498991212ae8248f3a7b97c9ceabe11c"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
